# Generated by Django 6.0.4 on 2026-04-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_area', models.FloatField(help_text='Area in square feet')),
                ('rooms', models.CharField(max_length=10)),
                ('material_quality', models.CharField(max_length=20)),
                ('paint_type', models.CharField(max_length=20)),
                ('house_type', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=30)),
                ('budget_range', models.CharField(max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
